feat:dynaimc iparams
freshworks-developers/configuration-page-samples pull request #13
Opened 2022-10-16 13:32 UTC by ajithajay

## Proposed changes

Added sample app to demonstrate the Dynamic Iparams for Freshteam

## Types of changes

- New feature - dynamic_iparams sample app for Freshteam

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/freshdesk/marketplace-sample-apps/blob/master/CONTRIBUTING.MD) doc
- [x] I run the app locally after the change. It works as expected.
- [x] I run the app after publishing it as a custom app after the change. It works as expected.

2022-10-17 14:08 UTC, zachjonesnoel requested changes
Please do the changes.

2022-10-17 14:08 UTC, zachjonesnoel commented on freshteam/dynamic_iparams/config/iparams.json
> +	"github_username": {
Please use camelcase - `githubUsername` so that all the keys are following the naming conventions.

2022-10-17 14:08 UTC, zachjonesnoel commented on freshteam/dynamic_iparams/config/iparams.json
> +	},
Is this to only demonstrate the `domain_name` and `api_key` types in installation parameters because I don't see them used anywhere else in the app?

2022-10-18 05:43 UTC, ajithajay commented on freshteam/dynamic_iparams/config/iparams.json
> +	"github_username": {
Sure, we will update the same

2022-10-18 09:46 UTC, ajithajay commented on freshteam/dynamic_iparams/config/iparams.json
> +	},
Yes, To demonstrate dynamic iparams we included domain_name & api_key. we don't have any specific logic/use case in the frontend. Also other sample also included the domain_name & api_key

2022-10-18 10:07 UTC, ajithajay commented on freshteam/dynamic_iparams/config/iparams.json
> +	"github_username": {
Hi, @zachjonesnoel renamed the key. Please review and update on the same

2022-10-19 06:10 UTC, ajithajay commented
Hi @zachjonesnoel , Is there any action item required from my end?

2022-10-19 08:36 UTC, zachjonesnoel commented
Hey @ajithajay, it looks good to me. Will close the PR and merge it soon. Thanks for taking it up and contributing with a sample app.

2022-10-19 17:08 UTC, merged